name: learn-github-actions
on: 
  - pull_request
jobs: 
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "Hello"
      - name: world
        run: echo " world!"
  goodbye-world:
    runs-on: ubuntu-latest
    needs: hello-world
    steps:
      - run: echo "Goodbye world!"